server:
  port: 8080
  context-path: /socialClub

spring:
# mysql database
  datasource:
    url: jdbc:mysql://localhost:3306/sams?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
# redis standalone
  redis:
    host: 192.168.186.132
    port: 6379


# shiro session and authorization cache
shiro:
  redis:
    expire: 30