server:
  port: 8080
  context-path: /socialClub

spring:
# mysql database
  datasource:
    url: jdbc:mysql://localhost:3306/sams?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
# redis standalone
  redis:
    cluster:
      nodes:
        - 192.168.186.132:7001
        - 192.168.186.132:7002
        - 192.168.186.132:7003
        - 192.168.186.132:7004
        - 192.168.186.132:7005
        - 192.168.186.132:7006
      maxIdle: 10
      minIdle: 5
      timeout: 3000
      maxRedirects: 6
      maxWaitMillis: 2000
      testOnReturn: true
      testOnBorrow: true



# shiro session and authorization cache
shiro:
  redis:
    expire: 30